### ISSUE TITLE
utf8.decode() is not a function error

### ISSUE THREAD

**Issue by Dnld** [mathiasbynens/utf8.js#17] opened 2016-06-14 20:21 UTC
Hi,

We've followed your instructions in the repo but cannot call the decode method.  Encode works fine.  Any insights as to why this might happen?

Thank you

**Comment by mathiasbynens** [comment] 2016-06-14 20:25
What have you tried exactly? What happens exactly?

**Comment by Dnld** [comment] 2016-06-14 20:40
We imported the package:

var utf8 = require('utf8');

then invoked the decode method on a string bytes from a base64 string (or any input) with utf8.decode(input) i get the error.

utf8.encode(input) works fine.

**Comment by mathiasbynens** [comment] 2016-06-14 20:41
Please provide a reduced test case so I can reproduce the error.

**Comment by Dnld** [comment] 2016-06-14 20:42
Unhandled JS Exception: utf8.decode is not a function. (In 'utf8.decode(bytes)', 'utf8.decode' is undefined)

**Comment by mathiasbynens** [comment] 2016-06-14 20:46
It’s hard to figure out what you’re doing exactly, unless you tell me.

It works fine for me:

```
$ npm i utf8

$ node -v
v6.2.1

$ node -p 'require("utf8").decode("\xE2\x99\xA5")'
♥
```

Since there appears to be no issue with utf8.js, I am closing this issue.

Provide a reduced test case and I’ll take a look.

**Closed by mathiasbynens** 2016-06-14 20:46 UTC

**Comment by txm** [comment] 2017-06-19 15:12
React Native problem?  I'm getting the same error as this chap.

https://stackoverflow.com/questions/41252188/react-native-how-to-decode-base64-encoded-string

**Comment by mcmar** [comment] 2017-06-27 23:21
@mathiasbynens the simplified test case is
```
react-native init DemoProj
cd DemoProj
yarn add utf8
```
then open `index.ios.js` and add the lines
```
import utf8 from 'utf8';
console.log(utf8);
```
then start the app using
```
react-native run-ios
```
then open the developer panel (⌘+D) and select "Debug JS Remotely"
That should open a panel in your web browser. Then press ⌘-⌥-i and select `console` to see the result of the `console.log` statement.

**Comment by mcmar** [comment] 2017-06-27 23:37
Looks like Facebook has a utility that takes precedence over this one when you do an `import` or `require`.
https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Utilities/utf8.js
#rude

**Comment by mcmar** [comment] 2017-06-27 23:39
@davidaurelio Got any suggestions for what to do about this?

**Comment by mcmar** [comment] 2017-06-27 23:44
@mathiasbynens Maybe consider also publishing this under `react-native-utf8` so us plebs can have access to your awesome library? Then leave a comment in the readme for react-native folks to know what to do. Can you even publish the same library under two namespaces? Is that allowed?

**Comment by davidaurelio** [comment] 2017-07-02 16:05
@mcmar can you send a PR for React Native to rename the internal module to something different?

**Comment by arribbar** [comment] 2017-12-06 16:36
well, I solved this error not using this project but the old method:
```
decodeURIComponent(escape(s))
```
